name: 'Markdown dead link inspector'
description: 'Checks for dead links in markdown files.'
author: 'Waqas Ali'

branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  path:
    description: 'Path to your markdown files'
    required: false
    default: './docs'
  useToken:
    description: 'Use a JWT token to authenticate requests'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
