name: Test Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
    
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          path: ./docs/**/*.md
